export const modules = [
  // --- Full Course Modules ---
  {
    id: 'O1_1',
    code: 'O1.1',
    title: 'Physiology Review',
    subtitle: 'Body systems relevant to injury assessment and clinical skills',
    courseTypes: ['full'],
    day: 'Monday',
    dayNumber: 1,
    sequence: 1,
    duration: '2.5 hours',
    instructor: 'SI',
    description: 'Core physiological principles underpinning dive medicine, covering respiratory, cardiovascular, and nervous system anatomy and function.',
    prerequisites: [],
    contentReady: true,
  },
  {
    id: 'O1_2',
    code: 'O1.2',
    title: 'Diving Physics',
    subtitle: 'Gas laws, pressure, and the physical principles of diving',
    courseTypes: ['full'],
    day: 'Monday',
    dayNumber: 1,
    sequence: 2,
    duration: '2 hours',
    instructor: 'SI',
    description: 'The physical laws governing diving including Boyle\'s, Dalton\'s, and Henry\'s laws, and their clinical relevance.',
    prerequisites: [],
    contentReady: true,
  },
  {
    id: 'O1_3',
    code: 'O1.3',
    title: 'DMT Role and Responsibilities',
    subtitle: 'Scope of practice, legal duties, and professional standards',
    courseTypes: ['full'],
    day: 'Monday',
    dayNumber: 1,
    sequence: 3,
    duration: '1 hour',
    instructor: 'SI',
    description: 'Understanding the role, responsibilities, and legal framework for Diver Medic Technicians in commercial and recreational diving.',
    prerequisites: [],
    contentReady: true,
  },
  {
    id: 'O1_4',
    code: 'O1.4',
    title: 'First Aid Principles',
    subtitle: 'Emergency first aid in the diving context',
    courseTypes: ['full'],
    day: 'Monday',
    dayNumber: 1,
    sequence: 4,
    duration: '2 hours',
    instructor: 'SI',
    description: 'First aid principles applied to the diving environment including primary and secondary surveys, oxygen administration, and casualty management.',
    prerequisites: [],
    contentReady: true,
  },
  {
    id: 'O2_1',
    code: 'O2.1',
    title: 'Gas Toxicity',
    subtitle: 'Oxygen toxicity, nitrogen narcosis, and CO2 retention',
    courseTypes: ['full'],
    day: 'Tuesday',
    dayNumber: 2,
    sequence: 1,
    duration: '2.5 hours',
    instructor: 'SI',
    description: 'Toxic effects of breathing gases under pressure, including oxygen toxicity, nitrogen narcosis, carbon dioxide retention, and carbon monoxide poisoning.',
    prerequisites: ['O1_1', 'O1_2'],
    contentReady: true,
  },
  {
    id: 'O2_2',
    code: 'O2.2',
    title: 'Barotrauma and Ear Problems',
    subtitle: 'Pressure injuries and otological conditions in diving',
    courseTypes: ['full'],
    day: 'Tuesday',
    dayNumber: 2,
    sequence: 2,
    duration: '2 hours',
    instructor: 'SI',
    description: 'Barotrauma affecting the ears, sinuses, lungs, and other gas-filled spaces, with emphasis on recognition and management.',
    prerequisites: ['O1_1', 'O1_2'],
    contentReady: true,
  },
  {
    id: 'O3_4',
    code: 'O3.4',
    title: 'Remaining Medical Topics',
    subtitle: 'Additional medical conditions relevant to diving',
    courseTypes: ['full'],
    day: 'Tuesday',
    dayNumber: 2,
    sequence: 3,
    duration: '2 hours',
    instructor: 'SI',
    description: 'Additional medical topics relevant to diving medicine including fitness to dive, contraindications, and return-to-diving criteria.',
    prerequisites: [],
    contentReady: true,
  },
  {
    id: 'O3_1',
    code: 'O3.1',
    title: 'Shock, Burns, and Blast Injury',
    subtitle: 'Recognition and management of trauma emergencies',
    courseTypes: ['full'],
    day: 'Wednesday',
    dayNumber: 3,
    sequence: 1,
    duration: '2 hours',
    instructor: 'SI',
    description: 'Recognition and management of shock in its various forms, burn injuries, and blast injury in the diving and offshore environment.',
    prerequisites: ['O1_4'],
    contentReady: true,
  },
  {
    id: 'O3_2',
    code: 'O3.2',
    title: 'Thermal Injury, Drowning, and Environmental',
    subtitle: 'Hypothermia, hyperthermia, drowning, and environmental hazards',
    courseTypes: ['full'],
    day: 'Wednesday',
    dayNumber: 3,
    sequence: 2,
    duration: '1.5 hours',
    instructor: 'SI',
    description: 'Thermal injuries, near-drowning, and environmental conditions affecting divers including hypothermia, hyperthermia, and marine envenomation.',
    prerequisites: ['O1_4'],
    contentReady: true,
  },
  {
    id: 'O2_3',
    code: 'O2.3',
    title: 'DCI and Diving Medicine',
    subtitle: 'Decompression illness: pathophysiology, recognition, and treatment',
    courseTypes: ['full', 'refresher'],
    day: 'Thursday',
    dayNumber: 4,
    sequence: 1,
    duration: '3 hours',
    instructor: 'DMP',
    description: 'Comprehensive coverage of decompression illness including pathophysiology, clinical presentation, differential diagnosis, and recompression treatment.',
    prerequisites: ['O1_1', 'O1_2'],
    contentReady: true,
    shared: true,
  },
  {
    id: 'O3_3',
    code: 'O3.3',
    title: 'Pharmacology and Drug Management',
    subtitle: 'Drug classes, administration, and management in diving medicine',
    courseTypes: ['full', 'refresher'],
    day: 'Thursday',
    dayNumber: 4,
    sequence: 2,
    duration: '2 hours',
    instructor: 'DMP',
    description: 'Pharmacology relevant to diving medicine, including drug classes, routes of administration, drug interactions, and management under pressure.',
    prerequisites: [],
    contentReady: true,
    shared: true,
  },
  // --- Refresher Modules ---
  {
    id: 'RM1',
    code: 'RM1',
    title: 'Resuscitation Update',
    subtitle: 'Current resuscitation guidelines and techniques',
    courseTypes: ['refresher'],
    day: 'Wednesday',
    dayNumber: 3,
    sequence: 1,
    duration: '1.5 hours',
    instructor: 'SI',
    description: 'Update on current resuscitation guidelines, including changes to protocols and new evidence-based practices.',
    prerequisites: [],
    contentReady: true,
  },
  {
    id: 'RM6',
    code: 'RM6',
    title: 'Casualty Care and Examination Review',
    subtitle: 'Systematic approach to casualty assessment',
    courseTypes: ['refresher'],
    day: 'Wednesday',
    dayNumber: 3,
    sequence: 2,
    duration: '1.5 hours',
    instructor: 'SI',
    description: 'Review of systematic casualty examination techniques and updates to clinical assessment procedures.',
    prerequisites: [],
    contentReady: true,
  },
  {
    id: 'RM5',
    code: 'RM5',
    title: 'Communications and Record Keeping',
    subtitle: 'Effective communication and documentation in diving operations',
    courseTypes: ['refresher'],
    day: 'Wednesday',
    dayNumber: 3,
    sequence: 3,
    duration: '1.5 hours',
    instructor: 'SI',
    description: 'Best practices in communication during diving operations and maintaining accurate medical records.',
    prerequisites: [],
    contentReady: true,
  },
  {
    id: 'RM4',
    code: 'RM4',
    title: 'New Techniques and Technology',
    subtitle: 'Recent advances in diving medicine and technology',
    courseTypes: ['refresher'],
    day: 'Wednesday',
    dayNumber: 3,
    sequence: 4,
    duration: '1.5 hours',
    instructor: 'SI',
    description: 'Overview of new techniques, equipment, and technological advances relevant to the DMT role.',
    prerequisites: [],
    contentReady: true,
  },
  {
    id: 'RM2',
    code: 'RM2',
    title: 'DCI Update',
    subtitle: 'Latest evidence and treatment protocols for decompression illness',
    courseTypes: ['refresher'],
    day: 'Thursday',
    dayNumber: 4,
    sequence: 1,
    duration: '3 hours',
    instructor: 'DMP',
    description: 'Update on decompression illness including latest research, treatment protocols, and case studies.',
    prerequisites: [],
    contentReady: true,
    shared: true,
    sharedWith: 'O2_3',
  },
  {
    id: 'RM3',
    code: 'RM3',
    title: 'Pharmacology Update',
    subtitle: 'Updates to pharmacological practice in diving medicine',
    courseTypes: ['refresher'],
    day: 'Thursday',
    dayNumber: 4,
    sequence: 2,
    duration: '2 hours',
    instructor: 'DMP',
    description: 'Update on pharmacological practices, new medications, and changes to drug management protocols.',
    prerequisites: [],
    contentReady: true,
    shared: true,
    sharedWith: 'O3_3',
  },
  {
    id: 'RM7',
    code: 'RM7',
    title: 'Diving Accidents and Incident Review',
    subtitle: 'Case studies and lessons from diving incidents',
    courseTypes: ['refresher'],
    day: 'Thursday',
    dayNumber: 4,
    sequence: 3,
    duration: '2 hours',
    instructor: 'SI',
    description: 'Review and analysis of diving accidents and incidents with learning points for improved practice.',
    prerequisites: [],
    contentReady: true,
  },

  // --- Full Course In-Person Modules (5 days at DDRC Plymouth) ---
  {
    id: 'IP1_1',
    code: 'IP1.1',
    title: 'Welcome, Admin, PPE and Infection Control',
    subtitle: 'Course registration, PPE donning/doffing, hand hygiene, and aseptic technique',
    courseTypes: ['full'],
    day: 'In-Person Day 1',
    dayNumber: 5,
    sequence: 1,
    duration: '1 hr 45 min',
    instructor: 'SI',
    description: 'Course registration and ID verification, PPE donning and doffing for clinical and hyperbaric environments, hand hygiene technique, and aseptic principles.',
    prerequisites: [],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'IP1_2',
    code: 'IP1.2',
    title: 'BLS Practical',
    subtitle: 'Basic life support, CPR, AED, and choking management',
    courseTypes: ['full'],
    day: 'In-Person Day 1',
    dayNumber: 5,
    sequence: 2,
    duration: '2 hours',
    instructor: 'SI',
    description: 'Practical basic life support including single-rescuer and team CPR, AED use, choking management, and recovery position.',
    prerequisites: ['O1_4'],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'IP1_3',
    code: 'IP1.3',
    title: 'Airway Management Station Rotation',
    subtitle: 'OPA, NPA, i-gel, BVM, suction, and oxygen delivery',
    courseTypes: ['full'],
    day: 'In-Person Day 1',
    dayNumber: 5,
    sequence: 3,
    duration: '1 hr 45 min',
    instructor: 'SI',
    description: 'Station rotation covering oropharyngeal and nasopharyngeal airways, i-gel insertion, bag-valve-mask ventilation, suction, and oxygen delivery systems.',
    prerequisites: ['O1_4'],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'IP1_4',
    code: 'IP1.4',
    title: 'Vital Signs Station Rotation',
    subtitle: 'Blood pressure, pulse oximetry, temperature, respiratory rate, and GCS',
    courseTypes: ['full'],
    day: 'In-Person Day 1',
    dayNumber: 5,
    sequence: 4,
    duration: '2 hours',
    instructor: 'SI',
    description: 'Practical vital signs measurement including manual and automatic blood pressure, pulse oximetry, temperature, respiratory rate, capillary refill, and GCS assessment.',
    prerequisites: ['O1_1'],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'IP2_1',
    code: 'IP2.1',
    title: 'Bleeding Control and Wound Management',
    subtitle: 'Direct pressure, tourniquets, haemostatic agents, and wound types',
    courseTypes: ['full'],
    day: 'In-Person Day 2',
    dayNumber: 6,
    sequence: 1,
    duration: '2 hours',
    instructor: 'SI',
    description: 'Bleeding control techniques including direct pressure, wound packing, tourniquet application, haemostatic agents, and wound assessment and cleaning.',
    prerequisites: ['O1_4'],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'IP2_2',
    code: 'IP2.2',
    title: 'Fractures, Splinting, and Evacuation',
    subtitle: 'Fracture recognition, splinting techniques, and casualty movement',
    courseTypes: ['full'],
    day: 'In-Person Day 2',
    dayNumber: 6,
    sequence: 2,
    duration: '2 hours',
    instructor: 'SI',
    description: 'Recognition and management of fractures and dislocations, splinting techniques, spinal immobilisation, and safe casualty evacuation methods.',
    prerequisites: ['O1_4'],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'IP2_3',
    code: 'IP2.3',
    title: 'Burns, Anaphylaxis, and Shock Practical',
    subtitle: 'Burn assessment, adrenaline administration, and shock management',
    courseTypes: ['full'],
    day: 'In-Person Day 2',
    dayNumber: 6,
    sequence: 3,
    duration: '1 hr 45 min',
    instructor: 'SI',
    description: 'Practical burn assessment and management, recognition and treatment of anaphylaxis including adrenaline auto-injector use, and shock recognition and management.',
    prerequisites: ['O3_1'],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'IP2_4',
    code: 'IP2.4',
    title: 'Neurological Examination, DMAC 01, and Communications',
    subtitle: 'Structured neuro exam, DMAC 01 documentation, SBAR and ATMIST',
    courseTypes: ['full'],
    day: 'In-Person Day 2',
    dayNumber: 6,
    sequence: 4,
    duration: '1 hr 45 min',
    instructor: 'SI',
    description: 'Structured neurological examination technique, completing the DMAC 01 form, and communication frameworks including SBAR and ATMIST for handover.',
    prerequisites: ['O1_1'],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'IP3_1',
    code: 'IP3.1',
    title: 'IV Cannulation, IO Access, and Fluid Administration',
    subtitle: 'Peripheral IV access, IO drill, and fluid management under pressure',
    courseTypes: ['full'],
    day: 'In-Person Day 3',
    dayNumber: 7,
    sequence: 1,
    duration: '1 hr 45 min',
    instructor: 'SI',
    description: 'Peripheral intravenous cannulation technique, intraosseous access using IO drill, fluid selection, rate calculation, and administration considerations in hyperbaric environments.',
    prerequisites: ['O3_3'],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'IP3_2',
    code: 'IP3.2',
    title: 'Injection Techniques and Drug Preparation',
    subtitle: 'IM, SC, and IV injection, drug drawing, and dose calculation',
    courseTypes: ['full'],
    day: 'In-Person Day 3',
    dayNumber: 7,
    sequence: 2,
    duration: '2 hours',
    instructor: 'SI',
    description: 'Intramuscular, subcutaneous, and intravenous injection techniques, drug preparation from ampoules and vials, dose calculation, and drug administration records.',
    prerequisites: ['O3_3'],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'IP3_3',
    code: 'IP3.3',
    title: 'Wound Closure: Suturing and Paper Stitches',
    subtitle: 'Simple interrupted sutures, wound closure strips, and wound care',
    courseTypes: ['full'],
    day: 'In-Person Day 3',
    dayNumber: 7,
    sequence: 3,
    duration: '1 hr 45 min',
    instructor: 'SI',
    description: 'Wound closure techniques including simple interrupted sutures, wound closure strips (Steri-Strips), wound irrigation, dressing selection, and aftercare.',
    prerequisites: [],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'IP3_4',
    code: 'IP3.4',
    title: 'Catheterisation, Ear Exam, ECG, and Viral Testing',
    subtitle: 'Urinary catheterisation, otoscopy, 12-lead ECG, and point-of-care testing',
    courseTypes: ['full'],
    day: 'In-Person Day 3',
    dayNumber: 7,
    sequence: 4,
    duration: '2 hours',
    instructor: 'DMP',
    description: 'Urinary catheterisation on manikins, otoscopic ear examination, 12-lead ECG lead placement and basic interpretation, and point-of-care viral and blood testing.',
    prerequisites: [],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'IP4_1',
    code: 'IP4.1',
    title: 'Hyperbaric Chamber Practical',
    subtitle: 'Chamber systems, operations, treatment tables, and casualty management under pressure',
    courseTypes: ['full'],
    day: 'In-Person Day 4',
    dayNumber: 8,
    sequence: 1,
    duration: '2.5 hours',
    instructor: 'SI',
    description: 'Recompression chamber familiarisation, chamber systems and safety, treatment table selection, gas management, and practical casualty management under hyperbaric conditions.',
    prerequisites: ['O2_3'],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'IP4_2',
    code: 'IP4.2',
    title: 'Diver Rescue, Bell Recovery, and Patient Movement',
    subtitle: 'In-water rescue, bell casualty extraction, stretcher and helicopter transfer',
    courseTypes: ['full'],
    day: 'In-Person Day 4',
    dayNumber: 8,
    sequence: 2,
    duration: '2 hours',
    instructor: 'SI',
    description: 'Diver rescue techniques, diving bell casualty extraction, stretcher packaging, helicopter transfer preparation, and patient movement in confined spaces.',
    prerequisites: [],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'IP4_3',
    code: 'IP4.3',
    title: 'DMAC 15 Kit Familiarisation',
    subtitle: 'Contents, layout, maintenance, and restocking of the DMAC 15 medical kit',
    courseTypes: ['full'],
    day: 'In-Person Day 4',
    dayNumber: 8,
    sequence: 3,
    duration: '1 hr 45 min',
    instructor: 'SI',
    description: 'DMAC 15 medical kit contents and layout, equipment checks, maintenance requirements, restocking procedures, and kit adaptation for different operations.',
    prerequisites: [],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'IP4_4',
    code: 'IP4.4',
    title: 'Formative Scenario 1 and Telemedicine Practical',
    subtitle: 'Integrated casualty scenario with telemedicine link to diving medical physician',
    courseTypes: ['full'],
    day: 'In-Person Day 4',
    dayNumber: 8,
    sequence: 4,
    duration: '2 hours',
    instructor: 'SI',
    description: 'Formative integrated scenario combining assessment, treatment, documentation, and telemedicine communication with a remote diving medical physician.',
    prerequisites: [],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'IP5_1',
    code: 'IP5.1',
    title: 'Written Examination',
    subtitle: 'Multiple choice and short answer exam, 70% pass mark',
    courseTypes: ['full'],
    day: 'In-Person Day 5',
    dayNumber: 9,
    sequence: 1,
    duration: '1 hr 45 min',
    instructor: 'SI',
    description: 'Invigilated written examination covering all course content. Multiple choice and short answer format, 1 hour duration, 70% pass mark required.',
    prerequisites: [],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'IP5_2',
    code: 'IP5.2',
    title: 'Assessed Integrative Scenario',
    subtitle: 'Summative practical assessment observed by independent examiner',
    courseTypes: ['full'],
    day: 'In-Person Day 5',
    dayNumber: 9,
    sequence: 2,
    duration: '2 hours',
    instructor: 'SI',
    description: 'Summative assessed scenario observed by an independent examiner. Candidates manage a realistic diving casualty from initial assessment through treatment and handover.',
    prerequisites: [],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'IP5_3',
    code: 'IP5.3',
    title: 'Open Skill Stations',
    subtitle: 'Supervised practice on any skill the candidate wishes to revisit',
    courseTypes: ['full'],
    day: 'In-Person Day 5',
    dayNumber: 9,
    sequence: 3,
    duration: '2 hours',
    instructor: 'SI',
    description: 'Open supervised practice session where candidates can revisit and practise any practical skill covered during the course.',
    prerequisites: [],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'IP5_4',
    code: 'IP5.4',
    title: 'Formative Scenario 2, Debrief, and Certification',
    subtitle: 'Final scenario, course debrief, feedback, and certificate issue',
    courseTypes: ['full'],
    day: 'In-Person Day 5',
    dayNumber: 9,
    sequence: 4,
    duration: '1 hr 45 min',
    instructor: 'SI',
    description: 'Second formative scenario for additional practice, whole-course debrief, candidate feedback, completion paperwork, and certificate issue.',
    prerequisites: [],
    contentReady: false,
    phase: 'in-person',
  },

  // --- Refresher In-Person Modules (2 days at DDRC Plymouth) ---
  {
    id: 'RD1_1',
    code: 'RD1.1',
    title: 'Welcome, Admin, and BLS/CPR Refresher',
    subtitle: 'Registration, ID verification, BLS algorithm, CPR, AED, and choking',
    courseTypes: ['refresher'],
    day: 'In-Person Day 1',
    dayNumber: 5,
    sequence: 1,
    duration: '2 hours',
    instructor: 'SI',
    description: 'Course registration, ID and DMT certificate verification, followed by BLS refresher including current algorithm, single-rescuer and team CPR, AED use, and choking management.',
    prerequisites: [],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'RD1_2',
    code: 'RD1.2',
    title: 'Airway Management Refresher Station Rotation',
    subtitle: 'OPA, NPA, i-gel, BVM, suction, and oxygen delivery refresher',
    courseTypes: ['refresher'],
    day: 'In-Person Day 1',
    dayNumber: 5,
    sequence: 2,
    duration: '2 hours',
    instructor: 'SI',
    description: 'Station rotation refreshing airway management skills including oropharyngeal and nasopharyngeal airways, i-gel, bag-valve-mask, suction, and oxygen delivery.',
    prerequisites: [],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'RD1_3',
    code: 'RD1.3',
    title: 'Vital Signs Refresher Station Rotation',
    subtitle: 'Blood pressure, pulse oximetry, temperature, respiratory rate, and GCS refresher',
    courseTypes: ['refresher'],
    day: 'In-Person Day 1',
    dayNumber: 5,
    sequence: 3,
    duration: '2 hours',
    instructor: 'SI',
    description: 'Refresher on vital signs measurement including blood pressure, pulse oximetry, temperature, respiratory rate, capillary refill, and GCS assessment.',
    prerequisites: [],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'RD1_4',
    code: 'RD1.4',
    title: 'Trauma Management Refresher',
    subtitle: 'Bleeding control, fractures, splinting, burns, and wound management',
    courseTypes: ['refresher'],
    day: 'In-Person Day 1',
    dayNumber: 5,
    sequence: 4,
    duration: '2 hours',
    instructor: 'SI',
    description: 'Refresher covering bleeding control, wound management, fracture recognition and splinting, burns assessment, and trauma casualty management.',
    prerequisites: [],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'RD1_5',
    code: 'RD1.5',
    title: 'Formative Scenario and Telemedicine Practical',
    subtitle: 'Integrated scenario with telemedicine link for skills refresh',
    courseTypes: ['refresher'],
    day: 'In-Person Day 1',
    dayNumber: 5,
    sequence: 5,
    duration: '1 hour',
    instructor: 'SI',
    description: 'Formative integrated scenario combining assessment, treatment, documentation, and telemedicine communication to refresh practical integration.',
    prerequisites: [],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'RD2_1',
    code: 'RD2.1',
    title: 'IV Cannulation, IO, and Fluid Administration Refresher',
    subtitle: 'IV access, IO drill, and fluid management refresher',
    courseTypes: ['refresher'],
    day: 'In-Person Day 2',
    dayNumber: 6,
    sequence: 1,
    duration: '2 hours',
    instructor: 'SI',
    description: 'Refresher on peripheral IV cannulation, intraosseous access, fluid selection, rate calculation, and administration under hyperbaric conditions.',
    prerequisites: [],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'RD2_2',
    code: 'RD2.2',
    title: 'Injection Techniques and Wound Closure Refresher',
    subtitle: 'IM, SC, IV injection, suturing, and wound closure refresher',
    courseTypes: ['refresher'],
    day: 'In-Person Day 2',
    dayNumber: 6,
    sequence: 2,
    duration: '2 hours',
    instructor: 'SI',
    description: 'Refresher on injection techniques, drug preparation, suturing, wound closure strips, and wound management.',
    prerequisites: [],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'RD2_3',
    code: 'RD2.3',
    title: 'DCI Neuro Exam, DMAC 01, and Communications',
    subtitle: 'Neurological examination, DMAC 01 completion, and SBAR/ATMIST refresher',
    courseTypes: ['refresher'],
    day: 'In-Person Day 2',
    dayNumber: 6,
    sequence: 3,
    duration: '2 hours',
    instructor: 'DMP',
    description: 'Refresher on structured neurological examination for DCI, completing the DMAC 01 form, and communication frameworks including SBAR and ATMIST.',
    prerequisites: [],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'RD2_4',
    code: 'RD2.4',
    title: 'Written Examination',
    subtitle: 'Multiple choice exam, 70% pass mark',
    courseTypes: ['refresher'],
    day: 'In-Person Day 2',
    dayNumber: 6,
    sequence: 4,
    duration: '1 hour',
    instructor: 'SI',
    description: 'Invigilated written examination covering refresher course content. Multiple choice format, 1 hour duration, 70% pass mark required.',
    prerequisites: [],
    contentReady: false,
    phase: 'in-person',
  },
  {
    id: 'RD2_5',
    code: 'RD2.5',
    title: 'Assessed Scenario, Catheterisation, Results, and Completion',
    subtitle: 'Summative scenario, catheterisation practical, results, and certification',
    courseTypes: ['refresher'],
    day: 'In-Person Day 2',
    dayNumber: 6,
    sequence: 5,
    duration: '3 hr 15 min',
    instructor: 'SI',
    description: 'Summative assessed scenario observed by independent examiner, catheterisation practical, exam results and feedback, completion paperwork, and certificate renewal.',
    prerequisites: [],
    contentReady: false,
    phase: 'in-person',
  },
]

export function getModulesForCourse(courseType) {
  return modules
    .filter((m) => m.courseTypes.includes(courseType))
    .sort((a, b) => a.dayNumber - b.dayNumber || a.sequence - b.sequence)
}

export function getModuleById(moduleId) {
  return modules.find((m) => m.id === moduleId) || null
}

export function getModulesByDay(courseType) {
  const courseModules = getModulesForCourse(courseType)
  const grouped = {}
  courseModules.forEach((m) => {
    if (!grouped[m.day]) grouped[m.day] = []
    grouped[m.day].push(m)
  })
  return grouped
}
