export const modules = [
  // --- Full Course Modules ---
  {
    id: 'O1_1',
    code: 'O1.1',
    title: 'Physiology Review',
    subtitle: 'Respiratory, cardiovascular, and nervous system fundamentals',
    courseTypes: ['full'],
    day: 'Monday',
    dayNumber: 1,
    sequence: 1,
    duration: '2.5 hours',
    instructor: 'SI',
    description: 'Core physiological principles underpinning dive medicine, covering respiratory, cardiovascular, and nervous system anatomy and function.',
    prerequisites: [],
    contentReady: false,
  },
  {
    id: 'O1_2',
    code: 'O1.2',
    title: 'Diving Physics',
    subtitle: 'Gas laws, pressure, and the physical principles of diving',
    courseTypes: ['full'],
    day: 'Monday',
    dayNumber: 1,
    sequence: 2,
    duration: '2 hours',
    instructor: 'SI',
    description: 'The physical laws governing diving including Boyle\'s, Dalton\'s, and Henry\'s laws, and their clinical relevance.',
    prerequisites: [],
    contentReady: false,
  },
  {
    id: 'O1_3',
    code: 'O1.3',
    title: 'DMT Role and Responsibilities',
    subtitle: 'Scope of practice, legal duties, and professional standards',
    courseTypes: ['full'],
    day: 'Monday',
    dayNumber: 1,
    sequence: 3,
    duration: '1 hour',
    instructor: 'SI',
    description: 'Understanding the role, responsibilities, and legal framework for Diver Medic Technicians in commercial and recreational diving.',
    prerequisites: [],
    contentReady: false,
  },
  {
    id: 'O1_4',
    code: 'O1.4',
    title: 'First Aid Principles',
    subtitle: 'Emergency first aid in the diving context',
    courseTypes: ['full'],
    day: 'Monday',
    dayNumber: 1,
    sequence: 4,
    duration: '2 hours',
    instructor: 'SI',
    description: 'First aid principles applied to the diving environment including primary and secondary surveys, oxygen administration, and casualty management.',
    prerequisites: [],
    contentReady: false,
  },
  {
    id: 'O2_1',
    code: 'O2.1',
    title: 'Gas Toxicity',
    subtitle: 'Oxygen toxicity, nitrogen narcosis, and CO2 retention',
    courseTypes: ['full'],
    day: 'Tuesday',
    dayNumber: 2,
    sequence: 1,
    duration: '2.5 hours',
    instructor: 'SI',
    description: 'Toxic effects of breathing gases under pressure, including oxygen toxicity, nitrogen narcosis, carbon dioxide retention, and carbon monoxide poisoning.',
    prerequisites: ['O1_1', 'O1_2'],
    contentReady: false,
  },
  {
    id: 'O2_2',
    code: 'O2.2',
    title: 'Barotrauma and Ear Problems',
    subtitle: 'Pressure injuries and otological conditions in diving',
    courseTypes: ['full'],
    day: 'Tuesday',
    dayNumber: 2,
    sequence: 2,
    duration: '2 hours',
    instructor: 'SI',
    description: 'Barotrauma affecting the ears, sinuses, lungs, and other gas-filled spaces, with emphasis on recognition and management.',
    prerequisites: ['O1_1', 'O1_2'],
    contentReady: false,
  },
  {
    id: 'O3_4',
    code: 'O3.4',
    title: 'Remaining Medical Topics',
    subtitle: 'Additional medical conditions relevant to diving',
    courseTypes: ['full'],
    day: 'Tuesday',
    dayNumber: 2,
    sequence: 3,
    duration: '2 hours',
    instructor: 'SI',
    description: 'Additional medical topics relevant to diving medicine including fitness to dive, contraindications, and return-to-diving criteria.',
    prerequisites: [],
    contentReady: false,
  },
  {
    id: 'O3_1',
    code: 'O3.1',
    title: 'Shock, Burns, and Blast Injury',
    subtitle: 'Recognition and management of trauma emergencies',
    courseTypes: ['full'],
    day: 'Wednesday',
    dayNumber: 3,
    sequence: 1,
    duration: '2 hours',
    instructor: 'SI',
    description: 'Recognition and management of shock in its various forms, burn injuries, and blast injury in the diving and offshore environment.',
    prerequisites: ['O1_4'],
    contentReady: false,
  },
  {
    id: 'O3_2',
    code: 'O3.2',
    title: 'Thermal Injury, Drowning, and Environmental',
    subtitle: 'Hypothermia, hyperthermia, drowning, and environmental hazards',
    courseTypes: ['full'],
    day: 'Wednesday',
    dayNumber: 3,
    sequence: 2,
    duration: '1.5 hours',
    instructor: 'SI',
    description: 'Thermal injuries, near-drowning, and environmental conditions affecting divers including hypothermia, hyperthermia, and marine envenomation.',
    prerequisites: ['O1_4'],
    contentReady: false,
  },
  {
    id: 'O2_3',
    code: 'O2.3',
    title: 'DCI and Diving Medicine',
    subtitle: 'Decompression illness: pathophysiology, recognition, and treatment',
    courseTypes: ['full', 'refresher'],
    day: 'Thursday',
    dayNumber: 4,
    sequence: 1,
    duration: '3 hours',
    instructor: 'DMP',
    description: 'Comprehensive coverage of decompression illness including pathophysiology, clinical presentation, differential diagnosis, and recompression treatment.',
    prerequisites: ['O1_1', 'O1_2'],
    contentReady: false,
    shared: true,
  },
  {
    id: 'O3_3',
    code: 'O3.3',
    title: 'Pharmacology and Drug Management',
    subtitle: 'Drug classes, administration, and management in diving medicine',
    courseTypes: ['full', 'refresher'],
    day: 'Thursday',
    dayNumber: 4,
    sequence: 2,
    duration: '2 hours',
    instructor: 'DMP',
    description: 'Pharmacology relevant to diving medicine, including drug classes, routes of administration, drug interactions, and management under pressure.',
    prerequisites: [],
    contentReady: false,
    shared: true,
  },
  // --- Refresher Modules ---
  {
    id: 'RM1',
    code: 'RM1',
    title: 'Resuscitation Update',
    subtitle: 'Current resuscitation guidelines and techniques',
    courseTypes: ['refresher'],
    day: 'Wednesday',
    dayNumber: 3,
    sequence: 1,
    duration: '1.5 hours',
    instructor: 'SI',
    description: 'Update on current resuscitation guidelines, including changes to protocols and new evidence-based practices.',
    prerequisites: [],
    contentReady: false,
  },
  {
    id: 'RM6',
    code: 'RM6',
    title: 'Casualty Care and Examination Review',
    subtitle: 'Systematic approach to casualty assessment',
    courseTypes: ['refresher'],
    day: 'Wednesday',
    dayNumber: 3,
    sequence: 2,
    duration: '1.5 hours',
    instructor: 'SI',
    description: 'Review of systematic casualty examination techniques and updates to clinical assessment procedures.',
    prerequisites: [],
    contentReady: false,
  },
  {
    id: 'RM5',
    code: 'RM5',
    title: 'Communications and Record Keeping',
    subtitle: 'Effective communication and documentation in diving operations',
    courseTypes: ['refresher'],
    day: 'Wednesday',
    dayNumber: 3,
    sequence: 3,
    duration: '1.5 hours',
    instructor: 'SI',
    description: 'Best practices in communication during diving operations and maintaining accurate medical records.',
    prerequisites: [],
    contentReady: false,
  },
  {
    id: 'RM4',
    code: 'RM4',
    title: 'New Techniques and Technology',
    subtitle: 'Recent advances in diving medicine and technology',
    courseTypes: ['refresher'],
    day: 'Wednesday',
    dayNumber: 3,
    sequence: 4,
    duration: '1.5 hours',
    instructor: 'SI',
    description: 'Overview of new techniques, equipment, and technological advances relevant to the DMT role.',
    prerequisites: [],
    contentReady: false,
  },
  {
    id: 'RM2',
    code: 'RM2',
    title: 'DCI Update',
    subtitle: 'Latest evidence and treatment protocols for decompression illness',
    courseTypes: ['refresher'],
    day: 'Thursday',
    dayNumber: 4,
    sequence: 1,
    duration: '3 hours',
    instructor: 'DMP',
    description: 'Update on decompression illness including latest research, treatment protocols, and case studies.',
    prerequisites: [],
    contentReady: false,
    shared: true,
    sharedWith: 'O2_3',
  },
  {
    id: 'RM3',
    code: 'RM3',
    title: 'Pharmacology Update',
    subtitle: 'Updates to pharmacological practice in diving medicine',
    courseTypes: ['refresher'],
    day: 'Thursday',
    dayNumber: 4,
    sequence: 2,
    duration: '2 hours',
    instructor: 'DMP',
    description: 'Update on pharmacological practices, new medications, and changes to drug management protocols.',
    prerequisites: [],
    contentReady: false,
    shared: true,
    sharedWith: 'O3_3',
  },
  {
    id: 'RM7',
    code: 'RM7',
    title: 'Diving Accidents and Incident Review',
    subtitle: 'Case studies and lessons from diving incidents',
    courseTypes: ['refresher'],
    day: 'Thursday',
    dayNumber: 4,
    sequence: 3,
    duration: '2 hours',
    instructor: 'SI',
    description: 'Review and analysis of diving accidents and incidents with learning points for improved practice.',
    prerequisites: [],
    contentReady: false,
  },
]

export function getModulesForCourse(courseType) {
  return modules
    .filter((m) => m.courseTypes.includes(courseType))
    .sort((a, b) => a.dayNumber - b.dayNumber || a.sequence - b.sequence)
}

export function getModuleById(moduleId) {
  return modules.find((m) => m.id === moduleId) || null
}

export function getModulesByDay(courseType) {
  const courseModules = getModulesForCourse(courseType)
  const grouped = {}
  courseModules.forEach((m) => {
    if (!grouped[m.day]) grouped[m.day] = []
    grouped[m.day].push(m)
  })
  return grouped
}
